In [89]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

train_df = pd.read_csv('./datasets/titanic_train.csv')
test_df = pd.read_csv('./datasets/titanic_test.csv')
test_y_df = pd.read_csv('./datasets/titanic_gender_submission.csv')

In [90]:
test_y_df

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [91]:
train_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [92]:
train = train_df[['Pclass', 'Sex', 'Age', 'Survived']]
test = test_df[['Pclass', 'Sex', 'Age']]
test_y = test_y_df['Survived']

In [93]:
train.isnull().sum()

Pclass        0
Sex           0
Age         177
Survived      0
dtype: int64

In [94]:
# 결측치 처리(제거)
train = train.dropna(axis=0)


In [95]:
train.isnull().sum()

Pclass      0
Sex         0
Age         0
Survived    0
dtype: int64

In [96]:
train.describe()

Pclass         Age    Survived
count  714.000000  714.000000  714.000000
mean     2.236695   29.699118    0.406162
std      0.838250   14.526497    0.491460
min      1.000000    0.420000    0.000000
25%      1.000000   20.125000    0.000000
50%      2.000000   28.000000    0.000000
75%      3.000000   38.000000    1.000000
max      3.000000   80.000000    1.000000

In [97]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 714 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    714 non-null    int64  
 1   Sex       714 non-null    object 
 2   Age       714 non-null    float64
 3   Survived  714 non-null    int64  
dtypes: float64(1), int64(2), object(1)
memory usage: 27.9+ KB


In [98]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
data = encoder.fit_transform(train['Sex'])
data

array([1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,

In [99]:
train['Sex'] = data

In [100]:
train.head()

Pclass  Sex   Age  Survived
0       3    1  22.0         0
1       1    0  38.0         1
2       3    0  26.0         1
3       1    0  35.0         1
4       3    1  35.0         0

In [101]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
data = scaler.fit_transform(train[['Age']])
train['Age'] = data

In [102]:
train.head()

Pclass  Sex       Age  Survived
0       3    1  0.271174         0
1       1    0  0.472229         1
2       3    0  0.321438         1
3       1    0  0.434531         1
4       3    1  0.434531         0

In [103]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

In [106]:
dt = DecisionTreeClassifier(random_state=42)
rf = RandomForestClassifier(random_state=42)
lr = LogisticRegression()

X = train.drop('Survived', axis=1)
y = train['Survived']

result_dict = {
    'dt' : [],
    'rf' : [],
    'lr' : []
}

for index, algorithm in enumerate([dt, rf, lr]) :
    result = cross_val_score(algorithm, X, y)
    if index == 0 :
        result_dict['dt'] = result
    elif index == 1 :
        result_dict['rf'] = result
    else :
        result_dict['lr'] = result
    print(result)


[0.77622378 0.81818182 0.8041958  0.81118881 0.83098592]
[0.76223776 0.8041958  0.83216783 0.83216783 0.82394366]
[0.74825175 0.83916084 0.77622378 0.74825175 0.80985915]


In [107]:
import numpy as np
print(np.mean(result_dict['dt']))
print(np.mean(result_dict['rf']))
print(np.mean(result_dict['lr']))

0.8081552250566336
0.8109425785482124
0.7843494533635379


In [108]:
test

Pclass     Sex   Age
0         3    male  34.5
1         3  female  47.0
2         2    male  62.0
3         3    male  27.0
4         3  female  22.0
..      ...     ...   ...
413       3    male   NaN
414       1  female  39.0
415       3    male  38.5
416       3    male   NaN
417       3    male   NaN

[418 rows x 3 columns]

In [109]:
test['Survived'] = test_y_df['Survived']
test

Pclass     Sex   Age  Survived
0         3    male  34.5         0
1         3  female  47.0         1
2         2    male  62.0         0
3         3    male  27.0         0
4         3  female  22.0         1
..      ...     ...   ...       ...
413       3    male   NaN         0
414       1  female  39.0         1
415       3    male  38.5         0
416       3    male   NaN         0
417       3    male   NaN         0

[418 rows x 4 columns]

In [110]:
test.dropna(axis=0, inplace=True)

In [112]:
test.isna().sum()

Pclass      0
Sex         0
Age         0
Survived    0
dtype: int64

In [113]:
encoder = LabelEncoder()
data = encoder.fit_transform(test['Sex'])
test['Sex'] = data

In [114]:
test.head()

Pclass  Sex   Age  Survived
0       3    1  34.5         0
1       3    0  47.0         1
2       2    1  62.0         0
3       3    1  27.0         0
4       3    0  22.0         1

In [115]:
scaler = MinMaxScaler()
data = scaler.fit_transform(test[['Age']])
test['Age'] = data

In [116]:
test.head()

Pclass  Sex       Age  Survived
0       3    1  0.452723         0
1       3    0  0.617566         1
2       2    1  0.815377         0
3       3    1  0.353818         0
4       3    0  0.287881         1

In [121]:
X_test = test.drop('Survived', axis = 1)
y_test = test['Survived']
rf.fit(X, y)
pred_rf = rf.predict(X_test)

In [122]:
pred_rf

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,

In [123]:
from sklearn.metrics import accuracy_score

accuracy_score(test['Survived'], pred_rf)

0.8403614457831325

In [124]:
dt.fit(X, y)
pred_dt = dt.predict(X_test)
accuracy_score(test['Survived'], pred_dt)

0.8192771084337349

In [125]:
lr.fit(X, y)
pred_lr = lr.predict(X_test)
accuracy_score(test['Survived'], pred_lr)

0.927710843373494